### PR TITLE
Added support for regex field & processor interface

### PR DESCRIPTION
**Pull request by ManiMozaffar**
- [x] Added simple regex support
- [x] Set default value on parser
- [x] Turn on/off default value for parser (since None can be default as well)
- [x] Fixed some parsing issue with XPATHField

### CODE REVIEW

**Comment by amirbahador-hub** [comment]
change processor to processors

**Comment by amirbahador-hub** [comment]
change interface to base

**Comment by amirbahador-hub** [comment]
check regex compling

**Comment by amirbahador-hub** [comment]
utilities to utils

**Comment by amirbahador-hub** [comment]
_lxml to lxml

**Comment by ManiMozaffar** [comment]
> check regex compling

I'll open an issue for this, let's handle it in another PR with appropriate benchmarking and discussion.

**Pull request merged**
